import type { MapData, RecordData, RankingEntry } from "./types";

export const MOCK_MAPS: MapData[] = [
  {
    id: "map-1",
    title: "CHAOS",
    artist: "Camellia",
    creator: { id: "u1", username: "MapMaster_KR", avatar: null },
    difficulty: 20,
    bpmMin: 200,
    bpmMax: 400,
    duration: 287,
    tileCount: 1024,
    coverImage: null,
    downloadUrl: "#",
    description: "An absolute nightmare of BPM changes and pattern density. Not for the faint-hearted.",
    tags: ["#speed", "#pattern", "#stream", "#technical"],
    status: "FEATURED",
    likeCount: 8420,
    playCount: 142000,
    bpmData: [
      { time: 0, bpm: 200 }, { time: 30, bpm: 220 }, { time: 60, bpm: 260 },
      { time: 90, bpm: 300 }, { time: 120, bpm: 400 }, { time: 150, bpm: 300 },
      { time: 180, bpm: 200 }, { time: 210, bpm: 350 }, { time: 240, bpm: 400 },
      { time: 270, bpm: 200 },
    ],
    createdAt: "2024-03-15T00:00:00Z",
  },
  {
    id: "map-2",
    title: "Shelter",
    artist: "Porter Robinson & Madeon",
    creator: { id: "u2", username: "EmotionBeats", avatar: null },
    difficulty: 7,
    bpmMin: 128,
    bpmMax: 128,
    duration: 218,
    tileCount: 456,
    coverImage: null,
    downloadUrl: "#",
    description: "A beautiful emotional journey through sound and tiles. Perfect for new players.",
    tags: ["#beginner-friendly", "#pattern"],
    status: "FEATURED",
    likeCount: 12400,
    playCount: 320000,
    bpmData: [
      { time: 0, bpm: 128 }, { time: 60, bpm: 128 }, { time: 120, bpm: 128 },
      { time: 180, bpm: 128 },
    ],
    createdAt: "2024-01-20T00:00:00Z",
  },
  {
    id: "map-3",
    title: "FREEDOM DiVE↓",
    artist: "xi",
    creator: { id: "u3", username: "xi_fan_2024", avatar: null },
    difficulty: 19,
    bpmMin: 222,
    bpmMax: 222,
    duration: 245,
    tileCount: 890,
    coverImage: null,
    downloadUrl: "#",
    description: "The legendary jump stream map. Constant 222.22 BPM will test your limit.",
    tags: ["#stream", "#speed", "#technical"],
    status: "APPROVED",
    likeCount: 6800,
    playCount: 98000,
    bpmData: Array.from({ length: 10 }, (_, i) => ({ time: i * 25, bpm: 222 })),
    createdAt: "2024-02-10T00:00:00Z",
  },
  {
    id: "map-4",
    title: "Ghost",
    artist: "Camellia",
    creator: { id: "u4", username: "CamelliaFan_JP", avatar: null },
    difficulty: 17,
    bpmMin: 174,
    bpmMax: 348,
    duration: 312,
    tileCount: 765,
    coverImage: null,
    downloadUrl: "#",
    description: "Intense BPM doubles and complex wave patterns. A true test of precision.",
    tags: ["#wave", "#precision", "#speed"],
    status: "FEATURED",
    likeCount: 9100,
    playCount: 167000,
    bpmData: [
      { time: 0, bpm: 174 }, { time: 45, bpm: 200 }, { time: 90, bpm: 260 },
      { time: 135, bpm: 348 }, { time: 180, bpm: 300 }, { time: 225, bpm: 348 },
      { time: 270, bpm: 174 }, { time: 300, bpm: 348 },
    ],
    createdAt: "2024-04-01T00:00:00Z",
  },
  {
    id: "map-5",
    title: "Through the Fire and Flames",
    artist: "DragonForce",
    creator: { id: "u5", username: "MetalMapper", avatar: null },
    difficulty: 16,
    bpmMin: 200,
    bpmMax: 200,
    duration: 441,
    tileCount: 1456,
    coverImage: null,
    downloadUrl: "#",
    description: "The iconic guitar shred marathon. Can you survive all 7+ minutes?",
    tags: ["#stream", "#stamina", "#speed"],
    status: "APPROVED",
    likeCount: 7200,
    playCount: 125000,
    bpmData: Array.from({ length: 15 }, (_, i) => ({ time: i * 30, bpm: 200 })),
    createdAt: "2024-01-05T00:00:00Z",
  },
  {
    id: "map-6",
    title: "Alt Futur",
    artist: "Silentroom",
    creator: { id: "u6", username: "SilentMapper", avatar: null },
    difficulty: 14,
    bpmMin: 155,
    bpmMax: 310,
    duration: 198,
    tileCount: 634,
    coverImage: null,
    downloadUrl: "#",
    description: "Smooth and technical with surprising BPM doublings. Great for improving timing.",
    tags: ["#technical", "#pattern", "#precision"],
    status: "APPROVED",
    likeCount: 4300,
    playCount: 72000,
    bpmData: [
      { time: 0, bpm: 155 }, { time: 40, bpm: 155 }, { time: 80, bpm: 310 },
      { time: 120, bpm: 155 }, { time: 160, bpm: 310 },
    ],
    createdAt: "2024-03-20T00:00:00Z",
  },
  {
    id: "map-7",
    title: "Mahou Shoujo no Refrein",
    artist: "Laur",
    creator: { id: "u7", username: "MagicalMapper", avatar: null },
    difficulty: 15,
    bpmMin: 188,
    bpmMax: 376,
    duration: 225,
    tileCount: 712,
    coverImage: null,
    downloadUrl: "#",
    description: "Magical aesthetic with brutal precision requirements. The double BPM hits hard.",
    tags: ["#precision", "#wave", "#technical"],
    status: "FEATURED",
    likeCount: 5600,
    playCount: 88000,
    bpmData: [
      { time: 0, bpm: 188 }, { time: 60, bpm: 188 }, { time: 90, bpm: 376 },
      { time: 120, bpm: 188 }, { time: 150, bpm: 376 }, { time: 200, bpm: 188 },
    ],
    createdAt: "2024-02-28T00:00:00Z",
  },
  {
    id: "map-8",
    title: "Routing",
    artist: "Camellia",
    creator: { id: "u1", username: "MapMaster_KR", avatar: null },
    difficulty: 21,
    bpmMin: 210,
    bpmMax: 420,
    duration: 267,
    tileCount: 1124,
    coverImage: null,
    downloadUrl: "#",
    description: "ULTRA tier. The routing of pure chaos. Only the top 0.1% have cleared this.",
    tags: ["#speed", "#stream", "#pattern", "#technical", "#spam"],
    status: "FEATURED",
    likeCount: 15000,
    playCount: 210000,
    bpmData: [
      { time: 0, bpm: 210 }, { time: 30, bpm: 300 }, { time: 60, bpm: 420 },
      { time: 90, bpm: 350 }, { time: 120, bpm: 420 }, { time: 150, bpm: 210 },
      { time: 180, bpm: 420 }, { time: 210, bpm: 350 }, { time: 240, bpm: 420 },
    ],
    createdAt: "2024-05-01T00:00:00Z",
  },
  {
    id: "map-9",
    title: "Stulti",
    artist: "BEMANI Sound Team vs Sota Fujimori",
    creator: { id: "u8", username: "BemaniMapper", avatar: null },
    difficulty: 11,
    bpmMin: 170,
    bpmMax: 170,
    duration: 167,
    tileCount: 498,
    coverImage: null,
    downloadUrl: "#",
    description: "Solid mid-difficulty map with consistent patterns and satisfying gameplay.",
    tags: ["#pattern", "#stream"],
    status: "APPROVED",
    likeCount: 3200,
    playCount: 58000,
    bpmData: Array.from({ length: 8 }, (_, i) => ({ time: i * 20, bpm: 170 })),
    createdAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "map-10",
    title: "Night Owl",
    artist: "Asking Alexandria",
    creator: { id: "u9", username: "RockMapper", avatar: null },
    difficulty: 9,
    bpmMin: 132,
    bpmMax: 264,
    duration: 198,
    tileCount: 387,
    coverImage: null,
    downloadUrl: "#",
    description: "Rock anthem with some tricky BPM halving. Great stepping stone to hard maps.",
    tags: ["#pattern", "#swing"],
    status: "APPROVED",
    likeCount: 2800,
    playCount: 45000,
    bpmData: [
      { time: 0, bpm: 132 }, { time: 60, bpm: 264 }, { time: 120, bpm: 132 },
      { time: 160, bpm: 264 },
    ],
    createdAt: "2024-03-01T00:00:00Z",
  },
  {
    id: "map-11",
    title: "Last Celebration",
    artist: "SOUND HOLIC",
    creator: { id: "u10", username: "SoundHolic_Fan", avatar: null },
    difficulty: 13,
    bpmMin: 185,
    bpmMax: 185,
    duration: 212,
    tileCount: 634,
    coverImage: null,
    downloadUrl: "#",
    description: "Dense and relentless. Every section demands your full attention.",
    tags: ["#stream", "#precision"],
    status: "APPROVED",
    likeCount: 4100,
    playCount: 67000,
    bpmData: Array.from({ length: 9 }, (_, i) => ({ time: i * 24, bpm: 185 })),
    createdAt: "2024-02-14T00:00:00Z",
  },
  {
    id: "map-12",
    title: "Stargazer",
    artist: "Yuki Kajiura",
    creator: { id: "u11", username: "AnimeMapper", avatar: null },
    difficulty: 5,
    bpmMin: 120,
    bpmMax: 120,
    duration: 235,
    tileCount: 278,
    coverImage: null,
    downloadUrl: "#",
    description: "Gentle and beautiful. Perfect introduction to custom maps.",
    tags: ["#beginner-friendly", "#slow"],
    status: "APPROVED",
    likeCount: 5500,
    playCount: 89000,
    bpmData: Array.from({ length: 6 }, (_, i) => ({ time: i * 40, bpm: 120 })),
    createdAt: "2024-01-01T00:00:00Z",
  },
];

export const MOCK_RANKINGS: RankingEntry[] = [
  {
    rank: 1,
    user: { id: "u1", username: "MapMaster_KR", avatar: null, country: "KR" },
    totalXp: 125000,
    mapsCleared: 156,
    avgAccuracy: 97.8,
    topAccuracy: 100,
  },
  {
    rank: 2,
    user: { id: "u3", username: "xi_fan_2024", avatar: null, country: "JP" },
    totalXp: 118000,
    mapsCleared: 143,
    avgAccuracy: 96.5,
    topAccuracy: 100,
  },
  {
    rank: 3,
    user: { id: "u4", username: "CamelliaFan_JP", avatar: null, country: "JP" },
    totalXp: 98000,
    mapsCleared: 128,
    avgAccuracy: 95.2,
    topAccuracy: 99.8,
  },
  {
    rank: 4,
    user: { id: "u7", username: "MagicalMapper", avatar: null, country: "US" },
    totalXp: 87000,
    mapsCleared: 112,
    avgAccuracy: 94.1,
    topAccuracy: 99.5,
  },
  {
    rank: 5,
    user: { id: "u2", username: "EmotionBeats", avatar: null, country: "CN" },
    totalXp: 76000,
    mapsCleared: 98,
    avgAccuracy: 93.8,
    topAccuracy: 99.2,
  },
  {
    rank: 6,
    user: { id: "u6", username: "SilentMapper", avatar: null, country: "US" },
    totalXp: 65000,
    mapsCleared: 87,
    avgAccuracy: 92.4,
    topAccuracy: 98.9,
  },
  {
    rank: 7,
    user: { id: "u5", username: "MetalMapper", avatar: null, country: "GB" },
    totalXp: 54000,
    mapsCleared: 74,
    avgAccuracy: 91.6,
    topAccuracy: 98.5,
  },
  {
    rank: 8,
    user: { id: "u8", username: "BemaniMapper", avatar: null, country: "JP" },
    totalXp: 48000,
    mapsCleared: 68,
    avgAccuracy: 90.2,
    topAccuracy: 98.1,
  },
  {
    rank: 9,
    user: { id: "u9", username: "RockMapper", avatar: null, country: "AU" },
    totalXp: 42000,
    mapsCleared: 61,
    avgAccuracy: 89.8,
    topAccuracy: 97.6,
  },
  {
    rank: 10,
    user: { id: "u10", username: "SoundHolic_Fan", avatar: null, country: "KR" },
    totalXp: 38000,
    mapsCleared: 55,
    avgAccuracy: 88.4,
    topAccuracy: 97.0,
  },
];

export const PLATFORM_STATS = {
  totalMaps: 4827,
  totalPlayers: 38400,
  totalRecords: 284000,
  todayRecords: 1240,
};
